from mcp_server import mcp

from .base import get, post, delete,put
from schemas.bus import AddBusInput
from schemas.bus import UpdateBusInput


import json

def get_all_buses_tool(token):
    
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = get("/admin/bus/get", headers=headers)
    
    return json.dumps(res.get("busInfo"))

def add_bus_tool( data: AddBusInput ):
    payload = {
        "name":data.name,
        "busnumber":data.busnumber,
        "totalseats": data.totalseats,
        "type":data.bus_type,
        "baseprice":data.baseprice,
        "amenties":data.amenties
    }

    headers = {
        "Authorization": f"Bearer {data.token}"
    }

    res = post("/admin/bus",payload=payload, headers=headers)

    return json.dumps(res)

def delete_bus_tool(token,busID):
    
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = delete(f"/admin/bus/{busID}", headers=headers)
    
    return json.dumps(res)

def update_bus_tool(data : UpdateBusInput):
    
    payload ={
        "id": data.id,
        "name": data.name,
        "baseprice": data.baseprice,
        "type":data.type,
        "amenties":data.amenties
    }
    
    headers = {
        "Authorization": f"Bearer {data.token}"
    }
    
    res = put(f"/admin/bus", payload=payload ,headers=headers)
    
    return json.dumps(res)

# --------------------------------------------------------- #

@mcp.tool()
def get_all_buses(token: str):
    """this tool return all the buses in the system, it required token that is generated by login tool"""
    
    return get_all_buses_tool(token)

@mcp.tool()
def add_bus(data:AddBusInput ):
    """this tool is used to add a new bus in the system"""

    return add_bus_tool(data)

@mcp.tool()
def update_bus(data: UpdateBusInput):
    """
    Updates an existing bus record.

    This API requires the complete bus object.
    All fields must be provided, even if they are not being changed.

    If a field is not intended to be updated, 
    its current (existing) value must be sent.

    The `id` field identifies the bus.
    A valid authentication token is required.
    """
    
    return update_bus_tool(data)

@mcp.tool()
def delete_bus(token: str , busId: str):
    """this tool delete the bus based on provided busId."""
    
    return delete_bus_tool(token,busId)