from .base import get, post, delete, put
import json
from schemas.route import AddRouteInput, EditRouteInput
from mcp_server import mcp



def get_all_routes_tool(token):
    
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = get("/admin/route/get", headers=headers)
    
    return json.dumps(res.get("routeInfo"))

def add_route_tool(data: AddRouteInput):

    headers = {
        "Authorization": f"Bearer {data.token}"
    }

    payload = {
        "stops": [s.model_dump() for s in data.stops]
    }

    res = post("/admin/route", payload=payload, headers=headers)
    
    return res

def update_route_tool(data: EditRouteInput):
    headers = {
        "Authorization": f"Bearer {data.token}"
    }

    payload = {
        "id": data.routeId,
        "stops": [s.model_dump() for s in data.stops],
    }

    res = put("/admin/route/update", payload=payload, headers=headers)

    return res

def delete_route_tool(token, routeID):
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = delete(f"/admin/route/{routeID}", headers=headers)
    
    return json.dumps(res)


# --------------------------------------------------------- #

@mcp.tool()
def get_all_routes(token: str):
    """this tool return all the routes in system, it requires token that is generated by login tool."""
    
    return get_all_routes_tool(token)

@mcp.tool()
def add_route(data: AddRouteInput):
    """this tool is used to add a new route in the system."""
    
    return add_route_tool(data)

@mcp.tool()
def update_route(data: EditRouteInput):
    """this tool updates an existing route using routeId and a full stops array."""

    return update_route_tool(data)

@mcp.tool()
def delete_route(token: str, routeID: str):
    """this tool delete the route based on provided routeID."""
    
    return delete_route_tool(token, routeID)
