from .base import get,delete, post, put
import json
from mcp_server import mcp

DAY_MAP = {
    "sun":0,"mon":1,"tue":2,"wed":3,"thu":4,"fri":5,"sat":6
}

def normalize_days(days):
    return [DAY_MAP[d.lower()[:3]] for d in days]


def get_all_trips_tool(token):
    
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = get("/trip/get", headers=headers)
    
    return json.dumps(res.get("trip"))

def find_available_resources_tool(
    route_id: str,
    departure_time: str,
    days: list[str],
    token: str
):
    days = normalize_days(days)

    headers = {
        "Authorization": f"Bearer {token}"
    }

    payload = { "routeId" :route_id , "departureTime" : departure_time, "days": days}

    available_bus = post("/trip/filterbus", payload, headers=headers).get("buses",[])
    available_drivers = post("/trip/filteremp", {**payload, "role": "driver"}, headers=headers).get("employees",[])
    available_conductors = post("/trip/filteremp", {**payload, "role": "conductor"}, headers=headers).get("employees",[])


    filtered_buses = [
        {
            "busId": bus.get("busId"),
            "name": bus.get("name")
        }
        for bus in available_bus
    ]

    filtered_drivers = [
        {
            "empId": driver.get("empId"),
            "empname": driver.get("empname")
        }
        for driver in available_drivers
    ]

    filtered_conductors = [
        {
            "empId": conductor.get("empId"),
            "empname": conductor.get("empname")
        }
        for conductor in available_conductors
    ]
    

    res = {
        "available_buses" : filtered_buses,
        "available_drivers" : filtered_drivers,
        "available_conductors" : filtered_conductors
    }

    return res

def add_trip_tool(
    route_id: str,
    bus_id: str,
    driver_id: str,
    conductor_id: str,
    departure_time: str,
    days: list[int],
    minimum_revenue: float,
    token: str
):
    days = normalize_days(days)

    headers = {
        "Authorization": f"Bearer {token}"
    }

    payload = {
        "routeId" : route_id,
        "busId" : bus_id,
        "driverId" : driver_id,
        "conductorId" : conductor_id,
        "departureTime" : departure_time,
        "days" : days,
        "minimumRevenue" : minimum_revenue
    }
    res = post("/trip", payload, headers)
    
    return json.dumps(res)

def update_trip_tool(
    trip_id : str,
    route_id: str,
    bus_id: str,
    driver_id: str,
    conductor_id: str,
    departure_time: str,
    days: list[str],
    minimum_revenue: float,
    token: str
):
    days = normalize_days(days)

    headers = {
        "Authorization": f"Bearer {token}"
    }

    payload = {
        "tripId": trip_id,
        "routeId" : route_id,
        "busId" : bus_id,
        "driverId" : driver_id,
        "conductorId" : conductor_id,
        "departureTime" : departure_time,
        "days" : days,
        "minimumRevenue" : minimum_revenue
    }

    res = put("/trip/update", payload, headers)
    
    return res

def delete_trips_tool(token, TripId):
    
    headers = {
        "Authorization": f"Bearer {token}"
    }
    
    res = delete(f"/trip/delete/{TripId}", headers=headers)
    
    return json.dumps(res)

# --------------------------------------------------------- #

@mcp.tool()
def get_all_trips(token: str):
    """this tool return all the trips in system, it requires token that is generated by login tool.
    trip is the main entity of travel which combine bus and route to make a one trip"""
    
    return get_all_trips_tool(token)

@mcp.tool()
def delete_trips(token: str, TripId: str):
    """this tool delete the trips based on TripId ."""
    
    return delete_trips_tool(token,TripId)

@mcp.tool()
def find_available_resources(
    route_id: str,
    departure_time: str,
    days: list[str],
    token: str
):
    """
    Returns available buses, drivers, and conductors for given route, time and days.
    useful before creating or updating a trip 

    days must be weekday names (3-letter lowercase):
    ["sun","mon","tue","wed","thu","fri","sat"]

    Examples:
    ["mon","fri"]
    ["sat","sun"]

    departure_time: "HH:MM AM/PM"
    """
    
    return find_available_resources_tool(route_id,departure_time,days,token)

@mcp.tool()
def add_trip(
    route_id: str,
    bus_id: str,
    driver_id: str,
    conductor_id: str,
    departure_time: str,
    days: list[str],
    minimum_revenue: float,
    token: str
):
    """
    Creates a trip after selecting resources.

    days must be weekday names (3-letter lowercase):
    ["sun","mon","tue","wed","thu","fri","sat"]

    Examples:
    ["mon","fri"]
    ["sat","sun"]

    departure_time: "HH:MM AM/PM"
    """


    return add_trip_tool(route_id,bus_id,driver_id,conductor_id,departure_time,days,minimum_revenue,token)

@mcp.tool()
def update_trip(
    trip_id : str,
    route_id: str,
    bus_id: str,
    driver_id: str,
    conductor_id: str,
    departure_time: str,
    days: list[str],
    minimum_revenue: float,
    token: str
):
    """
    Update a trip after selecting resources.

    days must be weekday names (3-letter lowercase):
    ["sun","mon","tue","wed","thu","fri","sat"]

    Examples:
    ["mon","fri"]
    ["sat","sun"]

    departure_time: "HH:MM AM/PM"
    """


    return update_trip_tool(trip_id,route_id,bus_id,driver_id,conductor_id,departure_time,days,minimum_revenue,token)

